# Generated by Django 2.0.1 on 2018-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='', max_length=200)),
                ('press', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('request_date', models.DateTimeField(default='2018-01-26 16:21')),
            ],
        ),
    ]
