# Generated by Django 2.0.1 on 2018-02-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawled_date', models.DateTimeField(default='2018-02-24 23:22')),
            ],
        ),
        migrations.CreateModel(
            name='NewsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_news_id', models.CharField(default='', max_length=50)),
                ('request_press', models.CharField(default='', max_length=20)),
                ('request_category', models.CharField(default='', max_length=20)),
                ('request_title', models.CharField(default='', max_length=200)),
                ('request_time', models.DateTimeField(default='2018-02-24 23:22')),
                ('is_scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='', max_length=200)),
                ('press', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('request_date', models.DateTimeField(default='2018-02-24 23:22')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=4)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('recommend_service', models.BooleanField(default=True)),
                ('remove_seen_news', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='newsrecord',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.UserStatus'),
        ),
    ]
