# Generated by Django 2.0.1 on 2018-03-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(default='', max_length=50)),
                ('feedback_content', models.TextField()),
                ('user_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.UserStatus')),
            ],
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-03-01 10:28'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='request_time',
            field=models.DateTimeField(default='2018-03-01 10:28'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-03-01 10:28'),
        ),
    ]
