# Generated by Django 2.0.1 on 2018-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180301_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='second_depth',
            field=models.CharField(default='건의사항', max_length=50),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-03-03 01:08'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='request_time',
            field=models.DateTimeField(default='2018-03-03 01:08'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-03-03 01:08'),
        ),
    ]
