# Generated by Django 2.0.1 on 2018-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180130_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-01-30 21:46'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-01-30 21:46'),
        ),
    ]
