# Generated by Django 2.0.1 on 2018-02-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180130_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='', max_length=200)),
                ('asked_news_title', models.CharField(default='', max_length=200)),
                ('asked_time', models.DateTimeField(default='2018-02-04 00:48')),
            ],
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-02-04 00:48'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-02-04 00:48'),
        ),
    ]
