# Generated by Django 2.0.1 on 2018-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180204_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsrequirement',
            old_name='asked_news_title',
            new_name='request_news_title',
        ),
        migrations.RemoveField(
            model_name='newsrequirement',
            name='asked_time',
        ),
        migrations.AddField(
            model_name='newsrequirement',
            name='request_news_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='newsrequirement',
            name='request_time',
            field=models.DateTimeField(default='2018-02-05 16:56'),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-02-05 16:56'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-02-05 16:56'),
        ),
    ]
