# Generated by Django 2.0.1 on 2018-02-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180205_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='', max_length=200)),
                ('gender', models.BooleanField(default=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('recommend_service', models.BooleanField(default=True)),
                ('remove_seen_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='newsrequirement',
            old_name='request_news_title',
            new_name='request_title',
        ),
        migrations.RemoveField(
            model_name='newsrequirement',
            name='user_key',
        ),
        migrations.AddField(
            model_name='newsrequirement',
            name='request_category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newsrequirement',
            name='request_press',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-02-11 01:19'),
        ),
        migrations.AlterField(
            model_name='newsrequirement',
            name='request_time',
            field=models.DateTimeField(default='2018-02-11 01:19'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-02-11 01:19'),
        ),
        migrations.AddField(
            model_name='newsrequirement',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.UserStatus'),
        ),
    ]
