# Generated by Django 2.0.1 on 2018-02-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180211_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_news_id', models.CharField(default='', max_length=50)),
                ('request_press', models.CharField(default='', max_length=20)),
                ('request_category', models.CharField(default='', max_length=20)),
                ('request_title', models.CharField(default='', max_length=200)),
                ('request_time', models.DateTimeField(default='2018-02-12 15:56')),
            ],
        ),
        migrations.RemoveField(
            model_name='newsrequirement',
            name='user_status',
        ),
        migrations.RenameField(
            model_name='userstatus',
            old_name='remove_seen_new',
            new_name='remove_seen_news',
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-02-12 15:56'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-02-12 15:56'),
        ),
        migrations.DeleteModel(
            name='NewsRequirement',
        ),
        migrations.AddField(
            model_name='newsrecord',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.UserStatus'),
        ),
    ]
