# Generated by Django 2.0.1 on 2018-02-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180212_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrecord',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crawlerdata',
            name='crawled_date',
            field=models.DateTimeField(default='2018-02-21 22:34'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='request_time',
            field=models.DateTimeField(default='2018-02-21 22:34'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-02-21 22:34'),
        ),
    ]
