# Generated by Django 2.0.1 on 2018-01-26 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.Document')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recomm', models.IntegerField()),
                ('unrecomm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.Document')),
                ('sentences_n', models.IntegerField()),
                ('text_rank', models.TextField()),
                ('word_count', models.TextField()),
                ('word_tfidf', models.TextField()),
                ('summary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentimentList',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.Document')),
                ('good', models.IntegerField()),
                ('warm', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('want', models.IntegerField()),
            ],
        ),
    ]
