# Generated by Django 2.0.1 on 2018-02-24 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentId',
            fields=[
                ('document_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recomm', models.IntegerField()),
                ('unrecomm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CultureLivingDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('sentences_n', models.IntegerField()),
                ('text_rank', models.TextField()),
                ('word_count', models.TextField()),
                ('word_tfidf', models.TextField()),
                ('summary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EconomicsDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='ITScienceDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='PoliticsDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='SentimentList',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('good', models.IntegerField()),
                ('warm', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('want', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocietyDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='WorldDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
    ]
