# Generated by Django 2.0.1 on 2018-02-04 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentId',
            fields=[
                ('document_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='document_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='document_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId'),
        ),
        migrations.AlterField(
            model_name='sentimentlist',
            name='document_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawler.DocumentId'),
        ),
        migrations.CreateModel(
            name='CultureLivingDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='EconomicsDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='ITScienceDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='PoliticsDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='SocietyDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.CreateModel(
            name='WorldDocument',
            fields=[
                ('documentid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.DocumentId')),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
            options={
                'abstract': False,
            },
            bases=('crawler.documentid',),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
