# Generated by Django 2.0.1 on 2018-02-04 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180204_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentid',
            name='category',
        ),
        migrations.RemoveField(
            model_name='documentid',
            name='press',
        ),
        migrations.RemoveField(
            model_name='documentid',
            name='published_date',
        ),
        migrations.AddField(
            model_name='culturelivingdocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturelivingdocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturelivingdocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='economicsdocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='economicsdocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='economicsdocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itsciencedocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itsciencedocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itsciencedocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='politicsdocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='politicsdocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='politicsdocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='societydocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='societydocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='societydocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worlddocument',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worlddocument',
            name='press',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worlddocument',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
